version: '3'
services:
  database:
    image: postgres:9
    ports:
      - "5432:5432"
    networks:
      - infra_postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  server:
    image: node:10
    ports:
      - "3000:3000"
    working_dir: "/storage"
    command: ["bash", "-c", "yarn && yarn start"]
    environment:
      PG_HOST: database
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - .:/storage/:z
    networks:
      - infra_postgres
      - infra_api
    depends_on: ["database"]

networks:
  infra_postgres:
  infra_api:

volumes:
  pg-data:
